// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         int    `json:"ID"`
	Name       string `json:"Name"`
	Surname    string `json:"Surname"`
	Patronymic string `json:"Patronymic"`
	Age        int    `json:"Age"`
	Gender     string `json:"Gender"`
	Country    string `json:"Country"`
}

type UserIn struct {
	ID         int     `json:"ID"`
	Name       *string `json:"Name,omitempty"`
	Surname    *string `json:"Surname,omitempty"`
	Patronymic *string `json:"Patronymic,omitempty"`
	Age        *int    `json:"Age,omitempty"`
	Gender     *string `json:"Gender,omitempty"`
	Country    *string `json:"Country,omitempty"`
}
