// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         *string `json:"ID,omitempty"`
	Name       string  `json:"Name"`
	Surname    string  `json:"Surname"`
	Patronymic *string `json:"Patronymic,omitempty"`
	Age        *int    `json:"Age,omitempty"`
	Gender     *string `json:"Gender,omitempty"`
	Country    *string `json:"Country,omitempty"`
}
